# Validate Tiles

In [4]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))

In [23]:
import cv2
import numpy as np
import shutil, os, sys, glob

from sklearn.metrics import confusion_matrix, jaccard_similarity_score

# Confusion matrix

In [22]:
datasets = ['xval_set_0',
            'xval_set_1',
            'xval_set_2',
            'xval_set_3',
            'xval_set_4',
          ]
appendage = '_1024'
size = 300

cfmats = []
for ds in datasets:
    predictions = sorted(glob.glob('/home/nathan/histo-seg/semantic-pca/analysis_segnet_basic/{}/*.png'.format(ds+appendage)))
    annotations = sorted(glob.glob('/home/nathan/histo-seg/semantic-pca/data/{}/val/mask/*.png'.format(ds)))
    
    print ds, len(predictions), len(annotations)
    
    preds = []
    annos = []
    for predx, annox in zip(predictions, annotations):
#         predx = predictions[0]
#         annox = annotations[0]
        preds.append(cv2.imread(predx,-1))
        annos.append(cv2.resize(cv2.imread(annox,-1), dsize=(size,size), interpolation=cv2.INTER_NEAREST))
        
    print len(preds), preds[0].shape#, preds[0].ravel().shape()
    print len(preds), annos[0].shape#, annos[0].ravel().shape()
    
    predimg = np.hstack([pimg.ravel() for pimg in preds])
    annoimg = np.hstack([aimg.ravel() for aimg in annos])
    cfmat = confusion_matrix(annoimg, predimg)
    print cfmat
    cfmats.append(cfmat)

cfmat_total = np.sum(cfmats, axis=0)
print cfmat_total

xval_set_0 103 103
103 (300, 300)
103 (300, 300)
[[ 591286  157805   83116  105235]
 [ 166685 2353664  116372  332565]
 [  39671   38883  672671   43403]
 [ 214771  336653  273722 3743498]]
xval_set_1 103 103
103 (300, 300)
103 (300, 300)
[[ 538482  186045   42364  111544]
 [ 232164 2486072   94418  477906]
 [  34726   61132  480638   53836]
 [ 147286  327531  126161 3869695]]
xval_set_2 102 102
102 (300, 300)
102 (300, 300)
[[ 566997  214553   28934   87942]
 [ 148719 2641193   53538  415592]
 [  79188  109450  410191   74153]
 [ 201239  665682  119380 3363249]]
xval_set_3 102 102
102 (300, 300)
102 (300, 300)
[[ 261106  159883   10308   45608]
 [ 142958 2692882   72331  329618]
 [  19227   65445  415380   81486]
 [  62734  489090   74684 4257260]]
xval_set_4 103 103
103 (300, 300)
103 (300, 300)
[[ 878559  154835   50198  131835]
 [ 234044 2188755  130447  403047]
 [  56352   18642  518633   77749]
 [ 295977  282848  135599 3712480]]
[[ 2836430   873121   214920   482164]
 [  924570 

# Jaccard directly

In [26]:
datasets = ['xval_set_0',
            'xval_set_1',
            'xval_set_2',
            'xval_set_3',
            'xval_set_4',
          ]
appendage = '_1024'
size = 300

jaccards = []
preds = []
annos = []
for ds in datasets:
    predictions = sorted(glob.glob('/home/nathan/histo-seg/semantic-pca/analysis_segnet_basic/{}/*.png'.format(ds+appendage)))
    annotations = sorted(glob.glob('/home/nathan/histo-seg/semantic-pca/data/{}/val/mask/*.png'.format(ds)))
    
    print ds, len(predictions), len(annotations)
    
#     preds = []
#     annos = []
    for predx, annox in zip(predictions, annotations):
#         predx = predictions[0]
#         annox = annotations[0]
        preds.append(cv2.imread(predx,-1))
        annos.append(cv2.resize(cv2.imread(annox,-1), dsize=(size,size), interpolation=cv2.INTER_NEAREST))
        
print len(preds), preds[0].shape#, preds[0].ravel().shape()
print len(preds), annos[0].shape#, annos[0].ravel().shape()

predimg = np.hstack([pimg.ravel() for pimg in preds])
annoimg = np.hstack([aimg.ravel() for aimg in annos])

for k in [0,1,2,3]:
    anno_ = annoimg==k
    pred_ = predimg==k
    print '\t', k, jaccard_similarity_score(anno_, pred_)

jaccard = jaccard_similarity_score(annoimg, predimg)
print '\t',jaccard
jaccards.append(jaccard)

# cfmat_total = np.sum(cfmats, axis=0)
# print cfmat_total

xval_set_0 103 103
xval_set_1 103 103
xval_set_2 102 102
xval_set_3 102 102
xval_set_4 103 103
513 (300, 300)
513 (300, 300)
	0 0.921032142084
	1 0.856641087286
	2 0.950944011263
	3 0.858677149664
	0.793647195148


In [27]:
np.mean([0.921, 0.8566, 0.9509, 0.8586])

0.89677499999999999